### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hide-sugi** [hide-sugi/furima-31773#10]
#URL
https://furima-31773.herokuapp.com/

#Basic認証のIDとパスワード
guest
5656

#出品者用のメールアドレスとパスワード
aa@aa
hide1200

#購入者用のメールアドレスとパスワード
ii@ii
hide1200

#購入用カードの番号・期限・セキュリティコード
4242424242424242
12月(20)24年
123

**Comment by tcamp1234** [comment]
hide-sugiさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◎商品購入機能
・商品購入ページでは、一覧や詳細ページで選択した商品の情報が出力されません
（出品した内容と画像が異なっております）
<img width="606" alt="スクリーンショット 2020-12-07 8 59 33" src="https://user-images.githubusercontent.com/64445215/101297260-79bcbb00-386b-11eb-8286-64870d6ae5d7.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hide-sugi** [comment]
ご返信ありがとうございます。

ご指摘箇所の修正をいたしました。ご確認よろしくお願いします。

**Comment by tcamp1234** [comment]
hide-sugiさん、ご提出ありがとうございます！
上記に関しまして正常に挙動しているのを確認致しました。
全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
